2018-08-19 00:35:55,590 ERROR 3736 nodejs.ClusterClientNoResponseError: client no response in 2043962ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 3736
hostname: USER-D8STTK4RDA

2018-08-19 00:36:05,556 ERROR 6204 nodejs.ECONNRESETError: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'ECONNRESETError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:29,528 ERROR 6204 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:29,562 ERROR 3736 nodejs.ClusterClientNoResponseError: client no response in 75513921ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 3736
hostname: USER-D8STTK4RDA

2018-08-19 21:34:32,349 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:32,505 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:32,715 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:32,969 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:33,274 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:33,635 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:34,062 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:34,523 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:35,030 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:35,670 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:36,275 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:36,939 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:37,644 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

2018-08-19 21:34:38,400 ERROR 6204 nodejs.ENETUNREACHError: connect ENETUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ENETUNREACH'
errno: 'ENETUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ENETUNREACHError'
pid: 6204
hostname: USER-D8STTK4RDA

