2018-08-23 10:18:32,552 ERROR 9244 nodejs.ClusterClientNoResponseError: client no response in 35321218ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\GitHub\egg_server\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 9244
hostname: USER-D8STTK4RDA

2018-08-23 10:18:32,660 ERROR 10196 nodejs.ECONNRESETError: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'ECONNRESETError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:32,715 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:32,842 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:35,140 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:35,345 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:35,615 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:35,969 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:36,354 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:36,775 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:37,283 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:37,998 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:38,560 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:39,169 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:39,828 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:40,533 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:41,297 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:42,104 ERROR 10196 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:18:52,972 ERROR 10196 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (D:\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:03,880 ERROR 10196 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (D:\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:14,853 ERROR 10196 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (D:\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:16,886 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:18,972 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:21,092 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:23,247 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:25,469 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:27,736 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:30,058 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:32,430 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:34,866 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:37,345 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:39,870 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:42,451 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:45,086 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:47,744 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:50,476 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:53,244 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:56,066 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:19:58,949 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:01,887 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:04,869 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:07,900 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:10,932 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:13,952 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:16,962 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:19,970 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:22,978 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:26,024 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:29,037 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:32,056 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:35,088 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:38,134 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:41,175 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:44,213 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:47,239 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:50,262 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:53,271 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:56,282 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:20:59,302 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:02,333 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:05,378 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:08,436 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:11,465 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:14,508 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:17,522 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:20,567 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:23,596 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:26,632 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:29,679 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:32,758 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:35,818 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:38,863 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:41,890 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:44,976 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:47,983 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:50,999 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:54,023 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:21:57,080 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:00,094 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:03,119 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:06,144 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:09,181 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:12,226 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:15,247 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:18,296 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:21,309 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:24,322 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:27,364 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:30,408 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:33,547 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:36,576 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:39,603 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:42,633 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:45,668 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:48,720 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:51,765 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:54,779 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:22:57,798 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:00,902 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:03,927 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:06,967 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:10,003 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:13,034 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:16,055 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:19,099 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:22,161 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:25,168 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:28,231 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:31,280 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:34,302 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:37,312 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:40,322 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:43,344 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:46,358 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:49,389 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:52,435 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:55,483 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:23:58,516 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:01,608 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:04,651 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:07,667 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:10,723 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:13,758 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:16,761 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:19,781 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:22,808 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:25,895 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:28,920 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:32,017 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:35,134 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:38,142 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:41,208 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:44,236 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:47,446 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:24:50,489 ERROR 10196 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10196
hostname: USER-D8STTK4RDA

2018-08-23 10:25:09,925 ERROR 10808 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10808
hostname: USER-D8STTK4RDA

2018-08-23 10:27:36,410 ERROR 5208 [-/127.0.0.1/-/190ms POST /api/getTestStatus] nodejs.ReferenceError: test_size is not defined
    at statusService.getTestStatusBytestid (D:\GitHub\egg_server\app\service\status.js:50:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
pid: 5208
hostname: USER-D8STTK4RDA

2018-08-23 10:29:09,665 ERROR 7000 [-/127.0.0.1/-/264ms POST /api/getTestStatus] nodejs.ReferenceError: testsize is not defined
    at statusService.getTestStatusBytestid (D:\GitHub\egg_server\app\service\status.js:51:88)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
pid: 7000
hostname: USER-D8STTK4RDA

2018-08-23 10:47:54,608 ERROR 8668 [-/127.0.0.1/-/297ms POST /api/getTestRankingList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'u.student_id' in 'where clause'
    at Query.Sequence._packetToError (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\GitHub\egg_server\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
    --------------------
    at Pool.query (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:199:23)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\GitHub\egg_server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (D:\GitHub\egg_server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (D:\GitHub\egg_server\node_modules\co\index.js:65:19)
    at D:\GitHub\egg_server\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (D:\GitHub\egg_server\node_modules\co\index.js:50:10)
    at RDSClient.createPromise [as query] (D:\GitHub\egg_server\node_modules\co\index.js:30:15)
    at TestLogService.getTestRankingList (D:\GitHub\egg_server\app\service\testLog.js:44:42)
    at StudentController.getTestRankingList (D:\GitHub\egg_server\app\controller\student.js:177:51)
    at Object.callFn (D:\GitHub\egg_server\node_modules\egg-core\lib\utils\index.js:36:21)
    sql: SELECT s.finish_time, s.start_time,
        timestampdiff(SECOND, s.start_time, s.finish_time) as time_consuming,
        s.correct_exercise, s.total_exercise, u.realname from test_log s,
        users u where s.test_id = '124' and u.student_id = s.userid and 
        s.correct_exercise is not null and s.finish_time is not null ORDER BY correct_exercise DESC LIMIT 7;
code: 'ER_BAD_FIELD_ERROR'
errno: 1054
sqlMessage: 'Unknown column \'u.student_id\' in \'where clause\''
sqlState: '42S22'
index: 0
sql: 'SELECT s.finish_time, s.start_time,\n        timestampdiff(SECOND, s.start_time, s.finish_time) as time_consuming,\n        s.correct_exercise, s.total_exercise, u.realname from test_log s,\n        users u where s.test_id = \'124\' and u.student_id = s.userid and \n        s.correct_exercise is not null and s.finish_time is not null ORDER BY correct_exercise DESC LIMIT 7;'
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
name: 'ER_BAD_FIELD_ERRORError'
pid: 8668
hostname: USER-D8STTK4RDA

2018-08-23 15:07:43,674 ERROR 5040 [-/127.0.0.1/-/201ms GET /api/getMyTestData?test_id=131&student_id=1] nodejs.ReferenceError: test_log_r is not defined
    at ExerciseLogService.getMyTestData (D:\GitHub\egg_server\app\service\exerciseLog.js:265:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
pid: 5040
hostname: USER-D8STTK4RDA

2018-08-23 15:26:16,731 ERROR 10208 nodejs.ECONNRESETError: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'ECONNRESETError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:17,802 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:18,936 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:20,089 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:21,340 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:22,629 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:23,949 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:25,320 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:26,842 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:28,360 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:29,874 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:31,490 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:33,122 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 15:26:34,828 ERROR 10208 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNREFUSED'
errno: 'ECONNREFUSED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNREFUSEDError'
pid: 10208
hostname: USER-D8STTK4RDA

2018-08-23 17:20:13,537 ERROR 12100 nodejs.ClusterClientNoResponseError: client no response in 78075ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\GitHub\egg_server\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 12100
hostname: USER-D8STTK4RDA

2018-08-23 17:20:41,628 ERROR 1840 [-/127.0.0.1/-/23952ms GET /api/getMyBookChapter?student_id=1&course_id=3] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (D:\GitHub\egg_server\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:48:16)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as getConnection] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at Pool.query (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:202:8)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\GitHub\egg_server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (D:\GitHub\egg_server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    sql: select b.bookid, b.bookname, c.chapterid, c.chaptername, sc.chapter_rating, cs.chapter_standard 
            from book b, 
            chapter c left join student_chapter sc on sc.chapterid = c.chapterid and sc.student_id = '1' 
                    left join chapter_standard cs on c.chapterid = cs.chapterid
            where b.course_id = '3' and c.bookid = b.bookid ORDER BY chindex
code: 'PROTOCOL_SEQUENCE_TIMEOUT'
fatal: true
timeout: 10000
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
name: 'PROTOCOL_SEQUENCE_TIMEOUTError'
pid: 1840
hostname: USER-D8STTK4RDA

2018-08-23 17:20:41,650 ERROR 1840 [-/127.0.0.1/-/15282ms GET /api/getCourse] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (D:\GitHub\egg_server\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:48:16)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as getConnection] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at Pool.query (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:202:8)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\GitHub\egg_server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (D:\GitHub\egg_server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    sql: SELECT * FROM `course`
code: 'PROTOCOL_SEQUENCE_TIMEOUT'
fatal: true
timeout: 10000
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
name: 'PROTOCOL_SEQUENCE_TIMEOUTError'
pid: 1840
hostname: USER-D8STTK4RDA

2018-08-23 17:20:41,655 ERROR 1840 [-/127.0.0.1/-/24097ms GET /api/getMyStudentRating?student_id=1&course_id=3] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (D:\GitHub\egg_server\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:48:16)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as getConnection] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at Pool.query (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:202:8)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\GitHub\egg_server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (D:\GitHub\egg_server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    sql: SELECT * FROM `student_rating` WHERE `student_id` = '1' AND `course_id` = '3' LIMIT 0, 1
code: 'PROTOCOL_SEQUENCE_TIMEOUT'
fatal: true
timeout: 10000
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
name: 'PROTOCOL_SEQUENCE_TIMEOUTError'
pid: 1840
hostname: USER-D8STTK4RDA

2018-08-23 17:22:13,547 ERROR 12100 nodejs.ClusterClientNoResponseError: client no response in 67137ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\GitHub\egg_server\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 12100
hostname: USER-D8STTK4RDA

2018-08-23 17:27:01,141 ERROR 1840 nodejs.ECONNABORTEDError: write ECONNABORTED (address: 127.0.0.1:50669)
    at _errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:780:25)
    at Socket._write (net.js:799:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:717:40)
    at Follower.sendHeartBeat (D:\GitHub\egg_server\node_modules\tcp-base\lib\base.js:105:18)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (D:\GitHub\egg_server\node_modules\tcp-base\lib\base.js:437:12)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
code: 'ECONNABORTED'
errno: 'ECONNABORTED'
syscall: 'write'
name: 'ECONNABORTEDError'
pid: 1840
hostname: USER-D8STTK4RDA

2018-08-23 17:27:12,431 ERROR 1840 [-/undefined/-/11190ms GET /api/getMyBookChapter?student_id=1&course_id=3] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (D:\GitHub\egg_server\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:48:16)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as getConnection] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at Pool.query (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:202:8)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\GitHub\egg_server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (D:\GitHub\egg_server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    sql: select b.bookid, b.bookname, c.chapterid, c.chaptername, sc.chapter_rating, cs.chapter_standard 
            from book b, 
            chapter c left join student_chapter sc on sc.chapterid = c.chapterid and sc.student_id = '1' 
                    left join chapter_standard cs on c.chapterid = cs.chapterid
            where b.course_id = '3' and c.bookid = b.bookid ORDER BY chindex
code: 'PROTOCOL_SEQUENCE_TIMEOUT'
fatal: true
timeout: 10000
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
headerSent: true
name: 'PROTOCOL_SEQUENCE_TIMEOUTError'
pid: 1840
hostname: USER-D8STTK4RDA

2018-08-23 17:27:12,441 ERROR 1840 [-/undefined/-/11238ms GET /api/getCourse] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (D:\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (D:\GitHub\egg_server\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:48:16)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as getConnection] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at Pool.query (D:\GitHub\egg_server\node_modules\mysql\lib\Pool.js:202:8)
    at D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (D:\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (D:\GitHub\egg_server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (D:\GitHub\egg_server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    sql: SELECT * FROM `course`
code: 'PROTOCOL_SEQUENCE_TIMEOUT'
fatal: true
timeout: 10000
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
headerSent: true
name: 'PROTOCOL_SEQUENCE_TIMEOUTError'
pid: 1840
hostname: USER-D8STTK4RDA

2018-08-24 11:32:57,797 ERROR 880 nodejs.ECONNRESETError: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'ECONNRESETError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:33:07,869 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:33:17,978 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:33:28,137 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:33:38,347 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:33:48,605 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:33:58,907 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:34:09,265 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:34:19,672 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:34:30,128 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:34:40,636 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:34:51,192 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:35:01,799 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:35:12,461 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:35:23,168 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:35:33,928 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:35:44,736 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:35:55,596 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:36:06,510 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:36:17,467 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:36:28,477 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:36:39,532 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:36:50,639 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:37:01,798 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:37:13,005 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:37:24,264 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:37:35,572 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:37:46,929 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:37:58,352 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:38:09,810 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:38:21,318 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:38:32,876 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:38:44,496 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:38:56,156 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:39:07,861 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:39:19,622 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:39:31,427 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:39:43,286 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:39:55,191 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:40:07,146 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:40:19,156 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:40:31,160 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:40:43,165 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:40:55,169 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:41:07,174 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:41:19,179 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:41:31,184 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:41:43,191 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:41:55,196 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:42:07,201 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:42:19,204 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:42:31,211 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:42:43,222 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:42:55,227 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:43:07,233 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:43:19,241 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:43:31,244 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:43:43,256 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:43:55,261 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:44:07,270 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:44:19,278 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:44:31,284 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:44:43,296 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:44:55,302 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:45:07,307 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:45:19,317 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:45:31,335 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:45:43,342 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:45:55,347 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:46:07,355 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:46:19,361 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:46:31,380 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:46:43,387 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:46:55,395 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:47:07,400 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:47:19,416 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:47:31,424 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 11:47:43,439 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:14:58,534 ERROR 5464 nodejs.ClusterClientNoResponseError: client no response in 1635108ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 5464
hostname: USER-D8STTK4RDA

2018-08-24 12:14:58,575 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:15:00,685 ERROR 880 nodejs.EHOSTUNREACHError: connect EHOSTUNREACH 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'EHOSTUNREACH'
errno: 'EHOSTUNREACH'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'EHOSTUNREACHError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:15:12,917 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:15:24,920 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:15:36,922 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:15:48,923 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:16:00,931 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:16:12,931 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:16:24,937 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:16:36,941 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:16:48,946 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:17:00,957 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:17:12,974 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:17:24,990 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:17:36,982 ERROR 880 nodejs.ETIMEDOUTError: connect ETIMEDOUT
    at Socket.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ioredis\lib\redis.js:289:21)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
errorno: 'ETIMEDOUT'
code: 'ETIMEDOUT'
syscall: 'connect'
name: 'ETIMEDOUTError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:17:43,137 ERROR 880 nodejs.ECONNABORTEDError: connect ECONNABORTED 119.23.41.237:6379
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
code: 'ECONNABORTED'
errno: 'ECONNABORTED'
syscall: 'connect'
address: '119.23.41.237'
port: 6379
name: 'ECONNABORTEDError'
pid: 880
hostname: USER-D8STTK4RDA

2018-08-24 12:22:49,597 ERROR 13800 nodejs.ClusterClientNoResponseError: client no response in 78902ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 13800
hostname: USER-D8STTK4RDA

2018-08-24 12:26:10,821 ERROR 13556 [-/172.20.10.3/-/272558ms POST /api/getTestRankingList] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:164:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\mysql\lib\protocol\sequences\Sequence.js:129:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
    --------------------
    at Protocol._enqueue (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\mysql\lib\Pool.js:48:16)
    at C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as getConnection] (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at Pool.query (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ali-rds\node_modules\pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    sql: SELECT s.finish_time, s.start_time,
        timestampdiff(SECOND, s.start_time, s.finish_time) as time_consuming,
        s.correct_exercise, s.total_exercise, u.realname from test_log s,
        users u where s.test_id = '124' and s.student_id = u.userid and 
        s.correct_exercise is not null and s.finish_time is not null ORDER BY correct_exercise DESC LIMIT 7
code: 'PROTOCOL_SEQUENCE_TIMEOUT'
fatal: true
timeout: 10000
headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true' }
name: 'PROTOCOL_SEQUENCE_TIMEOUTError'
pid: 13556
hostname: USER-D8STTK4RDA

2018-08-24 12:26:10,884 ERROR 13556 nodejs.ECONNABORTEDError: write ECONNABORTED (address: 127.0.0.1:58298)
    at _errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:780:25)
    at Socket._write (net.js:799:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:717:40)
    at Follower.sendHeartBeat (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\tcp-base\lib\base.js:105:18)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\Administrator\Documents\GitHub\egg_server\node_modules\tcp-base\lib\base.js:437:12)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
code: 'ECONNABORTED'
errno: 'ECONNABORTED'
syscall: 'write'
name: 'ECONNABORTEDError'
pid: 13556
hostname: USER-D8STTK4RDA

